const orderedDirectives = [
    'color',
    'font',
    'font-family',
    'font-size',
    'font-weight',
    'font-style',
    'font-variant',
    'font-size-adjust',
    'font-stretch',
    'font-effect',
    'font-emphasize',
    'font-emphasize-position',
    'font-emphasize-style',
    'font-smooth',
    'line-height',
    'text-align',
    'text-align-last',
    'text-decoration',
    'text-emphasis',
    'text-emphasis-color',
    'text-emphasis-style',
    'text-emphasis-position',
    'text-indent',
    'text-justify',
    'text-outline',
    'text-transform',
    'text-wrap',
    'text-overflow',
    'text-overflow-ellipsis',
    'text-overflow-mode',
    'text-shadow',
    'letter-spacing',
    'white-space',
    'word-spacing',
    'word-wrap',
    'word-break',
    'hyphens',
    'vertical-align',
    'content',
    'quotes',
    'resize',
    'cursor',
    'pointer-events',
    'user-select',
    'border',
    'border-width',
    'border-style',
    'border-color',
    'border-top',
    'border-top-width',
    'border-top-style',
    'border-top-color',
    'border-right',
    'border-right-width',
    'border-right-style',
    'border-right-color',
    'border-bottom',
    'border-bottom-width',
    'border-bottom-style',
    'border-bottom-color',
    'border-left',
    'border-left-width',
    'border-left-style',
    'border-left-color',
    'border-radius',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-bottom-right-radius',
    'border-bottom-left-radius',
    'border-image',
    'border-image-source',
    'border-image-slice',
    'border-image-width',
    'border-image-outset',
    'border-image-repeat',
    'outline',
    'outline-width',
    'outline-style',
    'outline-color',
    'outline-offset',
    'background',
    'background-color',
    'background-image',
    'background-repeat',
    'background-attachment',
    'background-position',
    'background-clip',
    'background-origin',
    'background-size',
    'box-decoration-break',
    'box-shadow',
    'gradient',
    'opacity',
    'position',
    'z-index',
    'top',
    'right',
    'bottom',
    'left',
    'display',
    'visibility',
    'float',
    'clear',
    'overflow',
    'overflow-x',
    'overflow-y',
    'clip',
    'zoom',
    'flex-basis',
    'flex-direction',
    'flex-order',
    'flex-pack',
    'flex-align',
    'flex-wrap',
    'flex-grow',
    'flex-shrink',
    'justify-content',
    'table-layout',
    'empty-cells',
    'caption-side',
    'border-spacing',
    'border-collapse',
    'list-style',
    'list-style-position',
    'list-style-type',
    'list-style-image',
    'box-sizing',
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'transition',
    'transition-delay',
    'transition-timing-function',
    'transition-duration',
    'transition-property',
    'transform',
    'transform-origin',
    'animation',
    'animation-name',
    'animation-duration',
    'animation-play-state',
    'animation-timing-function',
    'animation-delay',
    'animation-iteration-count',
    'animation-direction',
]

const directiveIndex = (directive: string) => {
	directive = directive.split(':')[0].trim()

	if (orderedDirectives.includes(directive)) {
		return orderedDirectives.indexOf(directive)
	} else if (directive === '') {
		return 5001
	} else {
		return 5000
    }
}

const sortStyles = (styles: Array<string>): Array<string> => {
	return styles.sort((a, b) => {
		const indexA = directiveIndex(a)
		const indexB = directiveIndex(b)
		return indexA < indexB ? -1 : indexA > indexB ? 1 : 0
	})
}

export {
    sortStyles
}
